version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --short --client
      - echo Installing AWS IAM Authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin
      # Install Clair scanner
      - echo Installing Clair scanner...
      - curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 > clair-scanner
      - chmod +x clair-scanner
      - mv clair-scanner /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Start Clair vulnerability database update (optional, depends on your Clair setup)
#      - echo Updating Clair vulnerability database...
#      - <command-to-update-clair-db>

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo dckr_pat_cPaUfLeeBued4VnzjeQKus3HOsQ | docker login --username za357627acc1 --password-stdin
      - docker build -t eks-cicd . 
      - docker tag eks-cicd:latest 024848438425.dkr.ecr.us-east-1.amazonaws.com/eks-cicd:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 024848438425.dkr.ecr.us-east-1.amazonaws.com
      - docker push 024848438425.dkr.ecr.us-east-1.amazonaws.com/eks-cicd:latest || (echo "docker push failed" && exit 1)
      # Scan the image with Clair
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name eks
      - kubectl config current-context
      - kubectl get nodes
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f k8s-deployment.yml
      - kubectl replace --force -f k8s-deployment.yml
      - kubectl get deployment

